# Default configuration for deploying Korrel8r as a service in an OpenShift cluster.
# Store service URLs assume that stores are installed in their default locations.
stores:
  - domain: k8s
  - domain: alert
    metrics: https://{{ .Metric }}.openshift-monitoring.svc:9091
    alertmanager: https://{{ .MetricAlert }}.openshift-monitoring.svc:9094
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: log
    lokiStack: https://{{ .Log }}.openshift-logging.svc:8080
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: metric
    metric: https://{{ .Metric }}.openshift-monitoring.svc:9091
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: netflow
    lokiStack: https://{{ .Netflow }}.netobserv.svc:8080
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt

include:
  - /etc/korrel8r/rules/all.yaml