apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: grover.home:5000/alanconway/observability-operator
  newTag: 3.3.3
commonAnnotations:
  package-operator.run/phase: operator
resources:
- ../../operator/
